#!/bin/sh
makepad(){
	printf "%-$((79 - $(wc -m <<<"$@") ))s\n" " "
}

ABULIA="Abulia Complete - $(date)"
IMON="$(uname -s -r -v)"
IAM="I am $(whoami) [$(getent passwd $(whoami) | cut -d ':' -f 5)] (id: $(id -u))"
HIJACK="Hijacked: $(whoami)@$(hostname) [$SHELL]"
MYLOC="Current Directory: $(pwd)"
ROOTLOC=$(lsblk -l -n -o NAME,MOUNTPOINT,FSTYPE,UUID | awk '$2 == "/" { printf "root on " $1 " (" $3 ") [" $4 "]" }' | sed -E 's/ +$//')
DISKUSE=$(lsblk -l -n -o NAME,MOUNTPOINT | awk '$2 == "/" {print "/dev/" $1}' | xargs df -h | tail -n 1 | awk '{ print "└ Size: " $2 " [Usage: " $3 "/" $2 " (" $5 ")]" }' )

if [ ! -f "/etc/ssh/sshd_config" ]; then

	SSHD_STR="no sshd config found in /etc/ssh/sshd_config";

elif [ -f "/etc/ssh/sshd_config" ]; then
	SSH_PORTS="Ports: "$(grep -Eo '^ *Port ([0-9]+) *$' <"/etc/ssh/sshd_config"  | awk '{ OUT=OUT ", " $2 }; END{print substr(OUT,3)}')
	SSH_PROTOCOL="SSH Protocol Version: "$(tac "/etc/ssh/sshd_config" | awk '$1 == "Protocol" { print $2 ; exit}')
	SSH_ALLOWROOT="Root Login Allowed: "$(tac "/etc/ssh/sshd_config" | awk '$1 == "PermitRootLogin" { print $2 ; exit}')
fi;


# TODO: the 'ROOTLOC' output spazzes out on thinner terminals.
cat <<EOF
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ $ABULIA$(makepad "$ABULIA")┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
┃ $IMON$(makepad "$IMON")┃
┃ $IAM$(makepad "$IAM")┃
┃ $HIJACK$(makepad "$HIJACK")┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
┃ $ROOTLOC$(makepad "$ROOTLOC")┃
┃ $DISKUSE$(makepad "$DISKUSE")┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
┃ SSH                                                                           ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
┃ $SSH_PORTS$(makepad "$SSH_PORTS")┃
┃ $SSH_PROTOCOL$(makepad "$SSH_PROTOCOL")┃
┃ $SSH_ALLOWROOT$(makepad "$SSH_ALLOWROOT")┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
EOF
